exclude: '^(.*egg.info.*|.*/parameters.py).*$'
default_language_version:
    python: python3
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
        exclude: '\.ambr$'
    -   id: end-of-file-fixer
    -   id: check-yaml
        exclude: .github/repo_meta.yaml
    -   id: debug-statements
-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
        - id: isort
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.18.0
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
        - id: black
          args:
              - --safe
              - --target-version
              - py38
          language_version: python3
-   repo: https://github.com/Lucas-C/pre-commit-hooks.git
    rev: v1.5.6
    hooks:
    -   id: insert-license
        name: insert-py-license
        files: >
            (?x)^(
                src/snowflake/sqlalchemy/.*\.py|
                tests/.*\.py|
                setup.py
            )$
        args:
            - --license-filepath
            - license_header.txt
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.16
    hooks:
    -   id: ruff
-   repo: local
    hooks:
      - id: requirements-update
        name: "Update dependencies from pyproject.toml to snyk/requirements.txt"
        language: system
        entry: python snyk/update_requirements.py
        files: ^pyproject.toml$
      - id: mypy
        name: mypy type check
        language: system
        entry: hatch run type-check
        pass_filenames: false
        types: [python]
