sudo: required
dist: xenial
language: python
matrix:
  include:
  - os: linux
    python: '3.5'
  - os: linux
    python: '3.6'
  - os: linux
    python: '3.7'
  - os: linux
    python: '3.7'
    env: SNOWFLAKE_AZURE=true
  - os: linux
    python: '3.7'
    env: SNOWFLAKE_GCP=true
install:
- "./scripts/install.sh"
script:
- "./scripts/run_travis.sh"
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - secure: buWiIuw+v2g3xBkLTqLSm1lHIfHRKsPo9c9C8K73swXsV5/puKq9xQiMlP8ZUgenWyXiU3Q2Xv3TvP43j0/mXA7CDhhXNVfTlVEOPF9zL64WuGy8LhFwmLF2bCZ/ZliFj+AEelyub1pmz94PihbG6pLsm9IUFMb4759Xg4t6qf6X4vjBYsWyX0xX8BNEJSgrzsZukndlCuGNwgl+UVhKeYs0DuB6K1hreVnUByScqQMBgSb82zG6XRzYMpOq8wHCsOQl8LZj6epe0q5j3gGZtEKyJcvZI/42aHto5b60mhHxFZj/mZFWtIiIs9Q/jzVr5jpr7sz38EqmErhZUNj63tQh4anNTJd6jI7nXC1CWsGqS1FvfgD8VqFrkcPXrjJrw12gpEpfY2KPst7epH65F+M+bKQU7QCxhMNwmq80eKvuCO75CzXDztzPwcG2M874IBo518iqQ2Uoy4VsA2uPYX5ZTHYT2q5nXcpZkJo5XxIBisyKkLKjkvMBKI+a+04WIO7xVW7Hq8J92BZwsbCbOMupUWDqGJ22VIR6C/ZVO0LNg/poMh2+I/BmL615/XSXkvae4rKTkl1uluetnJDEEsnUYEoKI5wEUavtQANOuUOIAL6698SZ2rotVlgJQCyS5GD3qJCOr0H7guGOu/+NRbhxVdlZf+yppjrm3fGRLw0=
  - secure: s/S2IVRdvtlfVbcUI+RC6Q0oc+6wXmyV3Bu0bDvAsMSXxbpil8YJym4YSrkFz4g3hvZ5NRQwDjPnj4XRFIVCGnN05JqD9HF+4oN+M6YTfVfv9DEZULIxSevDkn8UwZvTqvBIN2/kAhxV4urfXQ01E3aCFxVUY3y9IjONEirVW8345YOfbnkUan0JvIAizDI37eq/STBP9Lsp8m8ScrZ6MvAiqF5xaYM1hBejTybAhlGBzU9LOD5KDLWtie+v+C+UAYmwJwbbjBUDDx22oIq4cNTrSL5VDPw9O6e7MUDMyurfFkL4aOdO464JYRguqqoPkXZEUtwM6LQiF8Y0U6VP2ySTqy5eFJd61Hixr2JCAaZdreZEBMtdxQCcjdG5/Z6I2DLuQmq6QaiZnaL63vz8Y8XRhbMuHOjus14Fg47KRaopXCejsPYX333ftAcGZS6P+E4ev+5JsbKbTCNfXKSZy2bSwxF+akh0b+85DC+e+d4arACJPvBxSwkAUmNE32/oZrTECf0M1CLZ6YKNuxSonPP7+YmhNK0B1Q64ALaAZvPv7vjV5mXbgJt6S52wDoAYjRMWB9+S9BABTdOvF6HDE0HL6F0yJzdlnR/bsPdHfguygOQkk1fhSR4HhzfcmPExzH/s3vBPX8VIhKtGrm48ZYqGkdsIQfgfTYT5C49/Qvo=
  - secure: T60TJBwQpk57EgiaP1yDpJr6/EkWTIdbg4xAja2aJZCGuqkE5l6bcDBT0KcVhyRglfwz3oH/ej6B37ucXZ3TgtWieu38bNhjI37BPA/P8MKbPdkQVKf5Yj5U1BpWN0zu4Ud3yLAC90KF8EG1VMTwPrszZ/PCyxNwRnEU905DvaL/k8DzRilpPYWurtpbf/g2v92EXGif0wXrQSUCNOlh9wQEnt6QxRMguDTX/eVyg2eqj2T/5c9eHTm0bDYcws+nCYWdIR3BnqFXTLHs5/Hb6ejRfT8I0FcIr9xnOcYKxF8o1S+6ZhM23oyD+kJ3TOCJ6A7+IZqWk1gs74RMI5v5lPWKKakOU5nNeEJUFiBvMtOE36bYpOsKOHMhvaxyag0EcYEqwbepUgIQ39wJJvreVEDdNMWfLP6RP9j9l1a9/urtlDH5DXr4fUQ+gVRyvzXKNMqYdhSkm2INKcI7lC726aaGcRVN2DXZs7ckIyg4H2pbOeYPq6scm8oZh9HOGeazLgSESSQHGQFPzAXnAcbk4uLDN6y86U7FcYpatINuiEtmHokMvjt/Da14PCMgTsbHhDGXoQY4Avcz5IzshUm4TDGgg+mQCbEX0Ek5TK0MLaQe0cKZbkXiIngYcyPQz5AaVCDw4VqbCSJIGzpBownZ6BmJCCEq2NJY5AlXmgV9mu0=
