sudo: required
dist: xenial
language: python

matrix:
  include:
  - python: "2.7"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"

before_install:
  - sudo apt-get update
  - openssl aes-256-cbc -k "$super_secret_password" -in parameters.py.enc -out test/parameters.py -d

install:
  - ./scripts/install.sh

script:
  - ./scripts/run_travis.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    secure: buWiIuw+v2g3xBkLTqLSm1lHIfHRKsPo9c9C8K73swXsV5/puKq9xQiMlP8ZUgenWyXiU3Q2Xv3TvP43j0/mXA7CDhhXNVfTlVEOPF9zL64WuGy8LhFwmLF2bCZ/ZliFj+AEelyub1pmz94PihbG6pLsm9IUFMb4759Xg4t6qf6X4vjBYsWyX0xX8BNEJSgrzsZukndlCuGNwgl+UVhKeYs0DuB6K1hreVnUByScqQMBgSb82zG6XRzYMpOq8wHCsOQl8LZj6epe0q5j3gGZtEKyJcvZI/42aHto5b60mhHxFZj/mZFWtIiIs9Q/jzVr5jpr7sz38EqmErhZUNj63tQh4anNTJd6jI7nXC1CWsGqS1FvfgD8VqFrkcPXrjJrw12gpEpfY2KPst7epH65F+M+bKQU7QCxhMNwmq80eKvuCO75CzXDztzPwcG2M874IBo518iqQ2Uoy4VsA2uPYX5ZTHYT2q5nXcpZkJo5XxIBisyKkLKjkvMBKI+a+04WIO7xVW7Hq8J92BZwsbCbOMupUWDqGJ22VIR6C/ZVO0LNg/poMh2+I/BmL615/XSXkvae4rKTkl1uluetnJDEEsnUYEoKI5wEUavtQANOuUOIAL6698SZ2rotVlgJQCyS5GD3qJCOr0H7guGOu/+NRbhxVdlZf+yppjrm3fGRLw0=
