name: Semgrep

on:
  pull_request: {}

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v2
      - uses: returntocorp/semgrep-action@v1
        with:
          auditOn: push
          publishUrl: https://semgrep.snowflake.com
          publishDeployment: 1
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
